version: '3'
services:
  postgresql:
    image: "postgres:11-alpine"
    restart: always
    ports:
      - "9432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=canonical

      
