version: '3'
services:
  migrate-public:
    container_name: "compose-flyway-public"
    image: "boxfuse/flyway:latest"
    command: -url=jdbc:postgresql://postgresql:5432/canonical -schemas=public -table=public_versions -baselineOnMigrate=true -baselineVersion=0 -locations=filesystem:/flyway/sql/public -user=postgres -password=postgres -connectRetries=60  migrate
    volumes:
      - ./public/postgresql:/flyway/sql/public
    depends_on:
      - postgresql
